lang_skills = {
    "python": "Python",
    "cpp": "C++",
    "c": "C",
    "javascript": "JavaScript",
    "java": "Java",
    "php": "PHP",
    "rust": "Rust",
    "go": "Go",
    "dart": "Dart",
    "haskell": "Haskell",
    "swift": "Swift",
    "r": "R",
    "ruby": "Ruby",
    "kotlin": "Kotlin",
    "html": "HTML",
    "css": "CSS",
    "typescript": "TypeScript",
    "python": "Bash",
    "vba": "VBA",
    "scala": "Scala",
    "xml": "XML",
    "sql": "SQL",
    "powershell": "Powershell",
    "assembly": "Assembly",
    "matlab": "MATLAB",
    "lua": "Lua",
    "groovy": "Groovy",
    "delphi": "Delphi",
    "objective-c": "Objective-C",
    "perl": "Perl",
    "lisp": "LISP",
    "julia": "Julia",
    "clojure": "Clojure"
}

db_skills = {
    "mysql": "MySQL",
    "oracle": "Oracle",
    "sql-server": ["Microsoft SQL Server", "SQL Server"],
    "postgres": ["PostgreSQL", "Postgres"],
    "mongo": ["Mongo", "MongoDB"],
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "db2": ["IBM DB2", "DB2", "db2"],
    "access": "Microsoft Access",
    "sqlite": "SQLite",
    "cassandra": "Cassandra",
    "snowflake": "Snowflake",
    "mariadb": "MariaDB",
    "dynamodb": ["DynamoDB", "Amazon DynamoDB"],
    "splunk": "Splunk",
    "firestore": ["Firestore", "Google Firestore"],
    "firebase-realtime-database": ["Firebase Realtime Database"],
    "neo4j": "Neo4j",
    "couchbase": "Couchbase",
    "hive": "Hive",
    "bigquery": ["Google BigQuery", "BigQuery"],
    "memcached": "Memcached",

}

web_frameworks = {
    "django": "Django",
    "flask": "Flask",
    "nodejs": "Node.js",
    "react": "React.js",
    "angular": "Angular",
    "jquery": "jQuery",
    "express": "Express",
    "vue": "Vue.js",
    "asp.net-core": "ASP.NET Core",
    "asp.net": "ASP.NET",
    "nextjs": "Next.js",
    "laravel": "Laravel",
    "angularjs": "Angular.js",
    "fastapi": "FastAPI",
    "ruby-on-rails": "Ruby on Rails",
    "svelte": "Svelte",
    "blazor": "Blazor",
    "nuxtjs": "Nuxt.js",
    "symfony": "Symfony",
    "gatsby": "Gatsby",

}

other_libraries = {
    "tensorflow": "Tensorflow",
    ".net": ".NET",
    "apache-kafka": "Apache Kafka",
    "spark": "Apache Spark",
    "cordova": "Cordova",
    "electro": "Electron",
    "flutter": "Flutter",
    "gtk": "GTK",
    "hadoop": "Hadoop",
    "ionic": "Ionic",
    "keras": "Keras",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "qt": "Qt",
    "react-native": "React Native",
    "scikit-learn": "Scikit-learn",
    "spring": "Spring",
    "torch": "Torch/PyTorch",
    "xamarin": "Xamarin",
    "spring-boot": "Spring Boot",
    ".net-core": ".NET Core",
}

cloud_platforms = {
    "aws":"AWS",
    "digitalocean":"DigitalOcean",
    "firebase":"Firebase",
    "google-cloud":"Google Cloud",
    "heroku":"Heroku",
    "ibm":["IBM Cloud", "Watson", "IBM Watson"],
    "linode":"Linode",
    "managed":"Managed Hosting",
    "azure":"Microsoft Azure",
    "openstack":"OpenStack",
    "vmware":"VMware",
}

# devops = {}